# create secret
apiVersion: v1
kind: Secret
metadata:
  name: vault-configurations
  namespace: ${metadata_namespace}
type: Opaque
data:
  VAULT_ADDR: aHR0cDovL3ZhdWx0LWRldi52YXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo4MjAw
  AVP_TYPE: dmF1bHQ=
  AVP_AUTH_TYPE: azhz
  AVP_K8S_ROLE: YXJnb2Nk
#   AVP_K8S_MOUNT_PATH: Mount Path of your kubernetes Auth (optional)
#   AVP_K8S_TOKEN_PATH: Path to JWT (optional)


  